function [HR] = HR_k_fold(subsets)
%HR_K_FOLD Use k-fold cross-validation to measure the HR of LCF.
% input
% subsets: the k-fold subsets generated by "subsets_creating.m".
% output
% HR: the performance of LCF based on HR.

p = 1.5;   %personalization coefficient;
rank = 10;   %recommendation list length top-K;
k = size(subsets , 1);   %k-fold cross-validation;
HR = zeros(k , 1);   %initialize HR;
user_num = size(subsets , 2);   %user number;
item_num = size(subsets , 3);   %item number;
purchase_matrix = sum(subsets);   %the sum of the subsets is the complete dataset;
purchase_matrix = reshape(purchase_matrix(1 , : , :) , [] , size(purchase_matrix(1 , : , :) , 3));   %format conversion;

for r = 1 : k   %start cross-validation;
    test_matrix = reshape(subsets(r , : , :) , [] , size(subsets(r , : , :) , 3));   %generate testing set matrix;
    train_matrix = purchase_matrix - test_matrix;   %generate training set matrix;
    global_CTR = sum(train_matrix) ./ user_num;   %CTR for each item across all users in training set.
    R = (train_matrix' * train_matrix) ./ sum(train_matrix)' - global_CTR;   %correlation coefficient matrix, row i, column j;
    R(find(isnan(R) == 1)) = 0;   %replace NaN with 0;
    %calculate predicted click-through probability (pre_CTP);
    pre_CTP = p * (train_matrix * R) ./ sum(train_matrix , 2);
    pre_CTP(find(isnan(pre_CTP) == 1)) = 0;   %replace NaN with 0;
    pre_CTP = global_CTR + pre_CTP;
    pre_CTP = pre_CTP ./ (1 - train_matrix);   %convert the training set data to inf;
    pre_CTP(find(isinf(pre_CTP) == 1)) = nan;   %replace inf(training set data) with NaN;
    %generate top-K recommendations£»
    rank_matrix = zeros(user_num , item_num);
    [~ , index] = sort(pre_CTP , 2 , 'descend' , 'MissingPlacement' , 'last');   %each row is sorted in descending order;
    for i = 1 : user_num
        for j = 1 : rank
            rank_matrix(i , index(i , j)) = 1;
        end
    end
    HR(r) = sum(sum(rank_matrix .* test_matrix)) / (sum(sum(test_matrix)));   %calculate single HR;
end
HR = mean(HR);   %calculate mean HR;

