function [subsets] = subsets_creating(purchase_matrix)
%SUBSETS_CREATING Create the subsets for 5-fold cross-validation.
% input
% purchase_matrix: The user-item purchase matrix generated by 
% "matrix_creating.m".
% output
% subsets: Five equal subsets of the original interaction data in matrix
% form.

subsets = zeros(5 , size(purchase_matrix , 1) , size(purchase_matrix , 2));   %initialize subsets;
%divide the original data into five equal subsets by probability;
for i = 1 : size(purchase_matrix , 1)
    for j = 1 : size(purchase_matrix , 2)
        if purchase_matrix(i , j) == 1
            x = rand;
            if x < 0.2
                subsets(1 , i , j) = 1;
            elseif x < 0.4
                subsets(2 , i , j) = 1;
            elseif x < 0.6
                subsets(3 , i , j) = 1;
            elseif x < 0.8
                subsets(4 , i , j) = 1;
            else
                subsets(5 , i , j) = 1;
            end
        end
    end
end

end

